name: Deploy backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload backend files (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          source: "backend-api/*"
          target: "${{ secrets.EC2_PATH }}/backend-api"
          strip_components: 1

      - name: Deploy via SSH (PM2 reload)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          debug: true
          script: |
            set -e
            cd "${{ secrets.EC2_PATH }}/backend-api"
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm install -g pm2
            fi
            npm ci || npm install
            pm2 startOrReload ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
            pm2 save


