name: Deploy backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            set -e
            cd "${{ secrets.EC2_PATH }}/backend-api"
            git fetch --all
            git reset --hard origin/main
            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm install -g pm2
            fi
            npm ci || npm install
            pm2 startOrReload ecosystem.config.cjs --env production || pm2 start ecosystem.config.cjs --env production
            pm2 save
